services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
      SA_PASSWORD: "ChangeMe!12345!"
    volumes: ["mssql_data:/var/opt/mssql"]
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "/opt/mssql-tools18/bin/sqlcmd",
          "-S",
          "localhost",
          "-U",
          "sa",
          "-P",
          "ChangeMe!12345!",
          "-C",
          "-Q",
          "SELECT 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 10

  api:
    build: .
    depends_on:
      mssql:
        condition: service_healthy
    # Remove external port mapping - only Caddy will access it internally
    expose: ["8080"]
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      ConnectionStrings__DefaultConnection: "Server=mssql,1433;Database=HorusDb;User Id=sa;Password=ChangeMe!12345!;Encrypt=False;TrustServerCertificate=True;"
      JWT__SigningKey: "super-secret-jwt-signing-key-for-horus-api-2024-very-long-and-secure-key-that-meets-hmac-sha256-requirements-with-at-least-256-bits-32-characters-minimum-abcdefghijklmnopqrstuvwxyz-1234567890-ABCDEFGHIJKLMNOPQRSTUVWXYZ"
      CORS__Origins: "https://hoursteck.web.app"
    restart: unless-stopped

  caddy:
    image: caddy:2
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - api
    restart: unless-stopped

volumes:
  mssql_data:
  caddy_data:
  caddy_config:
