services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
      SA_PASSWORD: "ChangeMe!12345!"
    volumes: ["mssql_data:/var/opt/mssql"]
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "/opt/mssql-tools18/bin/sqlcmd",
          "-S",
          "localhost",
          "-U",
          "sa",
          "-P",
          "ChangeMe!12345!",
          "-C",
          "-Q",
          "SELECT 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 10

  api:
    build: .
    depends_on:
      mssql:
        condition: service_healthy
    ports: ["80:8080"]
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      ConnectionStrings__DefaultConnection: "Server=mssql,1433;Database=HorusDb;User Id=sa;Password=ChangeMe!12345!;Encrypt=False;TrustServerCertificate=True;"
      JWT__SigningKey: "replace-with-a-long-random-secret"
      CORS__Origins: "https://hoursteck.web.app,http://localhost:3000,https://localhost:3000"
    restart: unless-stopped

volumes:
  mssql_data:
